services:
  - type: web_service
    name: foody-api
    runtime: docker
    region: ohio
    plan: free
    rootDir: foody-laravel
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:h52pKGTS0UsyWDjDgS6jQF1TGLCcWVrn1oqxt4AUVrI=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d85o3uli849s738482sg-a.ohio-postgres.render.com
      - key: DB_DATABASE
        value: foody_db_xhgw
      - key: DB_USERNAME
        value: foody_db_xhgw_user
      - key: DB_PASSWORD
        value: kptR2Q3qAciddexM1qoH4K3iOElLZaHy
      - key: DB_PORT
        value: "5432"
      - key: FRONTEND_URL
        value: https://foody-full.vercel.app
      - key: SANCTUM_STATEFUL_DOMAINS
        value: foody-full.vercel.app
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_URL
        value: https://foody-api-7mag.onrender.com
      - key: MAIL_MAILER
        value: resend
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: noreply@foody.app
      - key: MAIL_FROM_NAME
        value: Foody Ocaña
