<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('restaurantes',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->onDelete('cascade');$t->string('nombre');$t->string('slug')->unique();$t->text('descripcion')->nullable();$t->string('categoria');$t->string('telefono',20)->nullable();$t->string('whatsapp',20)->nullable();$t->string('direccion');$t->decimal('lat',10,7)->nullable();$t->decimal('lng',10,7)->nullable();$t->string('foto_portada')->nullable();$t->string('logo')->nullable();$t->integer('tiempo_min')->default(20);$t->integer('tiempo_max')->default(40);$t->integer('pedido_minimo')->default(15000);$t->integer('radio_km')->default(5);$t->boolean('envio_gratis')->default(false);$t->integer('envio_gratis_desde')->nullable();$t->boolean('abierto')->default(true);$t->boolean('activo')->default(true);$t->decimal('rating',3,2)->default(0);$t->integer('total_resenas')->default(0);$t->timestamps();});
        Schema::create('horarios',function(Blueprint $t){$t->id();$t->foreignId('restaurante_id')->constrained()->onDelete('cascade');$t->string('dia',15);$t->time('hora_apertura');$t->time('hora_cierre');$t->boolean('activo')->default(true);$t->timestamps();});
        Schema::create('menu_categorias',function(Blueprint $t){$t->id();$t->foreignId('restaurante_id')->constrained()->onDelete('cascade');$t->string('nombre');$t->integer('orden')->default(0);$t->timestamps();});
        Schema::create('productos',function(Blueprint $t){$t->id();$t->foreignId('restaurante_id')->constrained()->onDelete('cascade');$t->foreignId('menu_categoria_id')->nullable()->constrained()->nullOnDelete();$t->string('nombre');$t->text('descripcion')->nullable();$t->integer('precio');$t->string('foto')->nullable();$t->string('emoji',10)->default('🍴');$t->boolean('disponible')->default(true);$t->integer('orden')->default(0);$t->timestamps();});
        Schema::create('direcciones',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->onDelete('cascade');$t->string('etiqueta')->default('Casa');$t->string('barrio');$t->string('calle');$t->string('detalle')->nullable();$t->text('indicaciones')->nullable();$t->decimal('lat',10,7)->nullable();$t->decimal('lng',10,7)->nullable();$t->boolean('principal')->default(false);$t->timestamps();});
        Schema::create('pedidos',function(Blueprint $t){$t->id();$t->string('referencia')->unique();$t->foreignId('user_id')->constrained()->onDelete('cascade');$t->foreignId('restaurante_id')->constrained()->onDelete('cascade');$t->foreignId('repartidor_id')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('direccion_id')->nullable()->constrained('direcciones')->nullOnDelete();$t->string('direccion_texto');$t->decimal('direccion_lat',10,7)->nullable();$t->decimal('direccion_lng',10,7)->nullable();$t->text('nota')->nullable();$t->integer('subtotal');$t->integer('costo_domicilio')->default(3500);$t->integer('descuento')->default(0);$t->integer('total');$t->string('metodo_pago',20);$t->string('estado',30)->default('pendiente');$t->string('codigo_cupon')->nullable();$t->timestamp('aceptado_at')->nullable();$t->timestamp('listo_at')->nullable();$t->timestamp('entregado_at')->nullable();$t->timestamps();});
        Schema::create('pedido_items',function(Blueprint $t){$t->id();$t->foreignId('pedido_id')->constrained()->onDelete('cascade');$t->foreignId('producto_id')->constrained()->onDelete('cascade');$t->string('nombre_snapshot');$t->integer('precio_snapshot');$t->integer('cantidad');$t->integer('subtotal');$t->timestamps();});
        Schema::create('pagos',function(Blueprint $t){$t->id();$t->foreignId('pedido_id')->constrained()->onDelete('cascade');$t->string('referencia_wompi')->nullable()->unique();$t->string('id_transaccion_wompi')->nullable();$t->string('metodo',30);$t->integer('monto');$t->string('estado',30)->default('pendiente');$t->json('respuesta_wompi')->nullable();$t->timestamp('pagado_at')->nullable();$t->timestamps();});
        Schema::create('cupones',function(Blueprint $t){$t->id();$t->string('codigo')->unique();$t->string('descripcion');$t->string('tipo',30);$t->integer('valor');$t->integer('minimo_pedido')->default(0);$t->integer('maximo_usos')->nullable();$t->integer('usos_actuales')->default(0);$t->timestamp('valido_desde')->nullable();$t->timestamp('valido_hasta')->nullable();$t->boolean('activo')->default(true);$t->timestamps();});
        Schema::create('resenas',function(Blueprint $t){$t->id();$t->foreignId('pedido_id')->constrained()->onDelete('cascade');$t->foreignId('user_id')->constrained()->onDelete('cascade');$t->foreignId('restaurante_id')->constrained()->onDelete('cascade');$t->tinyInteger('estrellas');$t->text('comentario')->nullable();$t->timestamps();});
        Schema::create('ubicaciones_repartidor',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->onDelete('cascade');$t->foreignId('pedido_id')->nullable()->constrained()->nullOnDelete();$t->decimal('lat',10,7);$t->decimal('lng',10,7);$t->boolean('en_linea')->default(false);$t->timestamp('actualizado_at')->useCurrent();$t->timestamps();});
        Schema::create('notificaciones',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->onDelete('cascade');$t->string('titulo');$t->string('mensaje');$t->string('tipo')->default('info');$t->string('icono')->nullable();$t->boolean('leida')->default(false);$t->json('data')->nullable();$t->timestamps();});
    }
    public function down(): void {
        foreach(['notificaciones','ubicaciones_repartidor','resenas','cupones','pagos','pedido_items','pedidos','direcciones','productos','menu_categorias','horarios','restaurantes'] as $t) Schema::dropIfExists($t);
    }
};
